### ISSUE TITLE
Path separator not handled correctly on Windows

### ISSUE THREAD

**Issue by thschalch** [editorconfig-checker/editorconfig-checker.python#27] opened 2023-08-28 10:53 UTC
My `.editorconfig` file looks as following:

```
root = true

[*]
trim_trailing_whitespace = true

[lib/**]
trim_trailing_whitespace = unset
```

I use the editorconfig-checker 2.7.2 from pip. On a Linux system, everything works as expected. Namely, the trailing whitespace rule is applied everywhere expect in all files and subfolders of the folder `lib`.

However, on Windows, this exception is ignored. Namely, I get some errors for the trailing whitespace rule inside the folder `lib`.

I found out that the tool works as expected on Windows if I change the line `[lib/**]` to `[lib\\**]`. But this is not an acceptable workaround for me, because I need the editorconfig-checker to behave exactly the same on Linux and on Windows. And it clearly violates the [editorconfig file format rules](https://spec.editorconfig.org/#file-format), saying that "Backslashes (\\) are not allowed as path separators (even on Windows)."

**Comment by mstruebing** [comment] 2023-08-28 11:01
Is that related? 
* https://github.com/editorconfig-checker/editorconfig-checker/issues/281
* https://github.com/editorconfig/editorconfig-core-go/issues/168

**Comment by thschalch** [comment] 2023-08-28 11:45
Yes, the effect is the same! I cannot assess whether it is the same bug in the `editorconfig-core-go` that propagates to the python package, but it really seems so.

**Comment by mstruebing** [comment] 2023-08-28 11:52
`editorconfig-checker.python` uses `editorconfig-checker` which uses `editorconfig-core-go` so if the issue is the same, it should be fixed when the issue in `editorconfig-core-go` is fixed.

**Comment by greut** [comment] 2023-08-29 12:50
@mstruebing it seems that `editorconfig-core-go` works fine with forward slashed files. You could change `filepath.Walk`^1^2 to use `fs.WalkDir`^3 instead or call `filepath.ToSlash`^4 on them, your call.

> `WalkDir` calls `fn` with paths that use *the separator character appropriate for the operating system*. This is unlike `io/fs.WalkDir`, which always uses slash separated paths. 
>
> https://pkg.go.dev/path/filepath#WalkDir

1. https://github.com/editorconfig-checker/editorconfig-checker/blob/main/pkg/files/files.go#L83
2. https://pkg.go.dev/path/filepath#Walk
3. https://pkg.go.dev/io/fs#WalkDir
4. https://pkg.go.dev/path/filepath#ToSlash

**Comment by mstruebing** [comment] 2023-08-30 07:37
Thank you @greut 

If anyone is willing to provide a PR I will make sure to get a new release out quickly.

**Comment by greut** [comment] 2023-09-27 09:32
One last error was present in the library, https://github.com/editorconfig/editorconfig-core-go/commit/73542738dcd64f432344079931e563e93a137b5f - So make sure you're sending _slash separated paths_ to it.

**Closed as completed** 2023-10-10 09:22 UTC
Labels: help wanted

**Comment by thschalch** [comment] 2023-10-16 10:52
I just tried out the new release 2.7.3 from pip, and things even get worse with the new release...

The initial example from above does still not work on Windows. Also the workarounds with `[lib\\**]` or with `[lib**]` both do not work anymore. It seems that any rule involving a path separator or `**` is not considered anymore!

EDIT: Also on Linux, the syntax `[lib/**]` does not work anymore with version 2.7.3.
